add cold-staking guides
NAVCoin/KnowledgeBase pull request #14
Opened 2020-02-13 22:24 UTC by chasingkirkjufell

2020-02-13 22:28 UTC, chasingkirkjufell commented
Preview https://deploy-preview-14--navcoin-knowledge-base.netlify.com/general-support/cold-staking/

2020-02-14 21:59 UTC, aguycalled requested changes

2020-02-14 21:59 UTC, aguycalled commented on content/General Support/cold staking.en.md
> +Cold-staking means that your wallet is not online staking and subject to attacks. Instead, a staking wallet which constains no NAV will be staking on behalf of your spending wallet which holds your N
s/constains/contains
s/nodes/node

2020-02-14 21:59 UTC, aguycalled commented on content/General Support/cold staking.en.md
> +After you send your coins to the cold-staking address, load your staking wallet with the mahcine you want to stake with (putting the wallet.dat file in the navcoin4 folder will do the trick). After s
s/mahcine/machine

2020-02-14 22:16 UTC, chasingkirkjufell commented on content/General Support/cold staking.en.md
> +Cold-staking means that your wallet is not online staking and subject to attacks. Instead, a staking wallet which constains no NAV will be staking on behalf of your spending wallet which holds your N
fixed in 50cd644

2020-02-14 22:16 UTC, chasingkirkjufell commented on content/General Support/cold staking.en.md
> +After you send your coins to the cold-staking address, load your staking wallet with the mahcine you want to stake with (putting the wallet.dat file in the navcoin4 folder will do the trick). After s
fixed in 50cd644

2020-02-14 22:17 UTC, aguycalled approved these changes

2020-02-14 22:17 UTC, merged